application: stocktradeanalyser
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /WebComponents
  static_dir: WebComponents

- url: /LoadMarketPrice
  script: main_loader.app

- url: /LoadMonthlyRevenue
  script: main_loader.app

- url: /LoadCompanyInfo
  script: main_loader.app

- url: .*
  script: main_stocktradeanalyser.app


libraries:
- name: webapp2
  version: "2.5.2"
