application: stocktradeanalyser
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /WebComponents
  static_dir: WebComponents

- url: /StockInfoLoader
  script: loader.app
  
- url: .*
  script: main_stocktradeanalyser.app


libraries:
- name: webapp2
  version: "2.5.2"
