version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    main_loader:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: simple
        filename: main_loader.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    main_page:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: simple
        filename: main_stockanalyser.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8


loggers:
    main_loader:
        level: DEBUG
        handlers: [main_loader]
        propagate: no

root:
    level: DEBUG
    handlers: [console, main_page]